token: {{ must_env `SLACK_TOKEN` }}
channel: "Cxxxxxx"
git_work_dir: "./"
pull_request_comment: "example"
pull_request_labels: ["example"]
mirage_url: "http://example.com"
docker_image: "example:master"
